package cn.lunalhx.ai.domain.agent.model.valobj;

public enum AgentStopReason {

    FINAL_ANSWER_RETURNED,
    STEP_LIMIT_REACHED,
    RETRY_LIMIT_REACHED,
    MODEL_ERROR,
    TIMEOUT,
    BUDGET_EXCEEDED,
    CONTEXT_OVERFLOW,
    USER_CANCELLED,
    RUNTIME_SCHEMA_MISMATCH,
    PERSISTENCE_ERROR,
    RESUME_ERROR,
    PLAN_SUBMITTED,
    PLAN_DEVIATION,
    PLAN_CONFLICT,
    PLAN_SUBMISSION_REJECTED

}
