package cn.lunalhx.ai.infrastructure.tool;

import cn.lunalhx.ai.domain.tool.model.ToolSpec;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public class ToolCatalogMarkdownRenderer {

    private static final String HEADER = """
            # Function Calling 工具目录

            本文件由 `ToolCatalogMarkdownRenderer` 自动生成，基于代码中所有内置、Context、Skill 和 Sub-Agent 工具的 `ToolSpec`。动态 MCP 工具不包含在内。

            **Schema Dialect**: [JSON Schema Draft 2020-12](https://json-schema.org/draft/2020-12)

            工具数量：%d

            ---
            """;

    private final ObjectMapper objectMapper;

    public ToolCatalogMarkdownRenderer(ObjectMapper objectMapper) {
        this.objectMapper = new ObjectMapper()
                .enable(SerializationFeature.INDENT_OUTPUT)
                .enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
    }

    public String render(Collection<ToolSpec> specs) {
        List<ToolSpec> sorted = specs.stream()
                .sorted(Comparator.comparing(ToolSpec::getName))
                .collect(Collectors.toList());

        StringBuilder sb = new StringBuilder();
        sb.append(String.format(HEADER, sorted.size()));

        for (int i = 0; i < sorted.size(); i++) {
            renderTool(sb, sorted.get(i), i + 1);
        }

        sb.append("\n*Generated by `ToolCatalogMarkdownRenderer`. Do not edit manually.*\n");
        return sb.toString();
    }

    private void renderTool(StringBuilder sb, ToolSpec spec, int index) {
        sb.append("## ").append(index).append(". `").append(spec.getName()).append("`");
        String category = categorize(spec.getName());
        sb.append(" (").append(category).append(")\n\n");
        sb.append(spec.getDescription()).append("\n\n");

        sb.append("<details>\n<summary>Schema</summary>\n\n```json\n");
        sb.append(formatSchema(spec.getInputSchema()));
        sb.append("\n```\n\n</details>\n\n---\n\n");
    }

    private String formatSchema(String schemaJson) {
        if (schemaJson == null || schemaJson.isBlank()) {
            return "{}";
        }
        try {
            JsonNode node = objectMapper.readTree(schemaJson);
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(node);
        } catch (Exception e) {
            return schemaJson;
        }
    }

    private String categorize(String toolName) {
        return switch (toolName) {
            case "spawn_agents", "sub_agent_dispatch" -> "Sub-Agent";
            case "context_recall" -> "Context";
            case "read_skill_resource", "copy_skill_resource", "create_skill", "activate_skill" -> "Skill";
            case "memory_save", "memory_search" -> "Memory";
            default -> "Built-in";
        };
    }
}
